# Generated by Django 3.2.4 on 2021-06-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContactos', '0002_auto_20210612_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='foto',
            field=models.ImageField(null=True, upload_to='contactos'),
        ),
    ]
